#!/bin/bash

echo "To convert Linux to RTC (Windows Format) push 1 and Enter"

echo "If you want to revert to default UTC push 2"

read value

if [ "$value" = "1" ]
then
	sudo timedatectl set-local-rtc 1 --adjust-system-clock
	echo "Configured OK. Now RTC like Windows OS."
	echo "Pros: No desyncronization in hour by dual boot"
else
	sudo timedatectl set-local-rtc 0 --adjust-system-clock
	echo "Default values saved. Now UTC."
fi