#!/bin/bash

####configAutologin

echo "Put the name/s of the user/s to auto-login preceding a blank space."
echo ""
echo "Example1: carl"
echo ""
echo "Example2: carl marie"
echo ""
echo "If you put only blank space, always will ask for pass for all users"
echo ""

read USER

FILE=/etc/lightdm/lightdm.conf

sudo sed -i "/autologin-user=/ s/$/$USER/" $FILE

read