#!/bin/bash

#1
#apt-get -y update && apt-get -y upgrade

#2
#apt-get -y --fix-broken install

#3
#apt-get -f install && apt-get -y autoremove && apt-get -y autoclean && apt-get -y clean
   
#4	  
#dpkg --configure -a && apt-get -y update

#5
#rm /var/lib/apt/lists/* -vf && apt-get -y update