#!/bin/bash

sudo apt-fast -y install mesa-common-dev libglu1-mesa-dev
wget http://download.qt.io/official_releases/qt/5.5/5.5.0/qt-opensource-linux-x64-5.5.0-2.run
sudo -s chmod u+x qt-opensource-linux-x64-5.5.0-2.run
sudo -s ./qt-opensource-linux-x64-5.5.0-2.run

#another ancient way
#to test

#https://qt-project.org/wiki/Install_Qt_5_on_Ubuntu																										
#http://www.wikihow.com/Install-Qt-SDK-on-Ubuntu-Linux

#sudo apt-get -y install "^libxcb.*" libx11-xcb-dev libglu1-mesa-dev libxrender-dev ### unofficial																												
#sudo apt-get -y install libgl1-mesa-dev libglu1-mesa-dev ### to test
#wget http://download.qt.io/official_releases/qt/5.5/5.5.0/qt-opensource-linux-x64-5.5.0-2.run
#sudo -s chmod u+x qt-opensource-linux-x64-5.5.0-2.run
#sudo -s ./qt-opensource-linux-x64-5.5.0-2.run -style cleanlooks																												
																														
#sudo -s chmod -R 777 /opt/Qt5.5.0																											
#sudo -s chmod -R 777 ~/.config/QtProject																												
																														
#sudo -s pluma /etc/profile																												
#PATH=/opt/Qt5.3.2/5.3.2/gcc/bin:$PATH																												
#export PATH																												
#. /etc/profile