#!/bin/bash

#### medigeek-kmp-downloader-f6a3c4e
sudo apt-get -y install python-bs4 python-apt
cd /tmp; rm -rf medigeek-kmp*; wget --no-check-certificate https://github.com/medigeek/kmp-downloader/tarball/master -O kmpd.tar.gz; tar xzf kmpd.tar.gz; cd medigeek-*; python kmpd.py -d
##python kmpd.py --help
##python kmpd.py -d
